In [6]:
import numpy as np


Question 1

In [16]:
L=np.random.randint(0,100,(4,4))
print(L)
#print(L.shape)
n_row=L.shape[0]
n_col=L.shape[1]

liste=[]
for i in range(n_row):
    for j in range(n_col):
        liste.append(L[i][j])
print(liste)

[[93 16 79 21]
 [98 39 26 24]
 [83 81 47 86]
 [39 87 79 30]]
[93, 16, 79, 21, 98, 39, 26, 24, 83, 81, 47, 86, 39, 87, 79, 30]


Question 2


In [21]:
L=np.random.randint(0,100,(4,4))
print(L)

def somme_A(L) :
    n_row=L.shape[0]
    n_col=L.shape[1]
    somme=0
    for i in range(n_row):
        somme=somme+L[i][i]
    return somme


print("he sum of the diagonal element is ",somme_A(L))
        
        

[[74 11  3 16]
 [91 78 82  5]
 [72 38 66 64]
 [62 39 58 25]]
he sum of the diagonal element is  243


Question 3

In [25]:
def higher(m,x):
    m_row=m.shape[0]
    m_col=m.shape[1]
    for i in range(m_row):
        for j in range(m_col):
            if m[i][j]>x:
                print(m[i][j],"located at",(i,j),"is higher than",x)
m=np.random.randint(0,100,(4,4))
print(m)
higher(m,50)

[[99 47 56 16]
 [45 46 84 18]
 [29 34 51 62]
 [52 93 97 15]]
99 located at (0, 0) is higher than 50
56 located at (0, 2) is higher than 50
84 located at (1, 2) is higher than 50
51 located at (2, 2) is higher than 50
62 located at (2, 3) is higher than 50
52 located at (3, 0) is higher than 50
93 located at (3, 1) is higher than 50
97 located at (3, 2) is higher than 50


Question 4

In [40]:
def add_array(m1,m2):
    m1_row=m1.shape[0]
    m1_col=m1.shape[1]
    m2_row=m1.shape[0]
    m2_col=m1.shape[1]
    if (m1_row != m2_row) or (m1_col != m2_col):
        print("the arrays don't have the same shape")
    else:
        m3=np.random.randint(0,1,(m1_row,m1_col))
        for i in range(m1_row):
            for j in range(m1_col):
                m3[i][j]=m1[i][j]+m2[i][j]
    return m3

m1=np.random.randint(0,10,(4,4))
m2=np.random.randint(0,10,(4,4))


print(m1)
print("")
print(m2)
print("")
m3=add_array(m1,m2)
print(m3)
    
    

[[7 6 2 6]
 [8 0 1 0]
 [8 0 1 4]
 [0 9 2 6]]

[[9 5 2 7]
 [1 8 4 9]
 [8 0 3 7]
 [4 0 8 4]]

[[16 11  4 13]
 [ 9  8  5  9]
 [16  0  4 11]
 [ 4  9 10 10]]


Question 5

In [42]:
def substract_array(m):
    m_row=m1.shape[0]
    m_col=m1.shape[1]
    somme=0
    for i in range(m_row):
        for j in range(m1_col):
            somme=somme+m[i][j]
        mean=(somme/m_row)
        for j in range(m_col):
            m[i][j]=m[i][j]-mean
    return (m)
m=np.random.randint(0,10,(4,4))
print(m)
print(" ")
m1=substract_array(m)
print(m1)


            
    

[[1 1 6 4]
 [8 0 7 4]
 [9 1 4 7]
 [4 6 9 1]]
 
[[ -2  -2   3   1]
 [  0  -7   0  -3]
 [ -4 -12  -9  -6]
 [-14 -12  -9 -17]]
